### ISSUE TITLE
Create PUT method with replace semantics

### ISSUE THREAD

**Issue by rob-deans** [IBM-Swift/GeneratedSwiftServer#11]
The current implementation is for PUT is actually a PATCH implementation and we should rename it and create the PUT method as well

update() ~~PUT~~ PATCH /location/{id}
replace() PUT /location/{id}

**Comment by rob-deans** [comment]
Related PR: #12

**Comment by tunniclm** [comment]
Implemented in #12 -- this is a breaking change and we should ensure the next tag increments the minor version.

Note: we can't update the generator to the new version until CloudantStore is updated (IBM-Swift/GeneratedSwiftServer-CloudantStore#4).

**Comment by tunniclm** [comment]
Tagged version 0.2.0 for this. Will open an issue on generator-swiftserver for updating to 0.2.x when CloudantStore is ready.
